### YamlMime:ManagedReference
items:
- uid: StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability
  commentId: T:StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability
  id: XCodeCapabilitySettings.BackgroundModesCapability
  parent: StansAssets.IOS.XCode
  children:
  - StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.Options
  langs:
  - csharp
  - vb
  name: XCodeCapabilitySettings.BackgroundModesCapability
  nameWithType: XCodeCapabilitySettings.BackgroundModesCapability
  fullName: StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability
  type: Class
  source:
    id: BackgroundModesCapability
    path: ''
    startLine: 1620
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.IOS.XCode
  syntax:
    content: 'public class BackgroundModesCapability : XCodeCapabilitySettings.Capability'
    content.vb: >-
      Public Class BackgroundModesCapability
          Inherits XCodeCapabilitySettings.Capability
  inheritance:
  - System.Object
  - StansAssets.IOS.XCode.XCodeCapabilitySettings.Capability
  inheritedMembers:
  - StansAssets.IOS.XCode.XCodeCapabilitySettings.Capability.Enabled
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.ReferenceEquals(System.Object,System.Object)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.Options
  commentId: F:StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.Options
  id: Options
  parent: StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability
  langs:
  - csharp
  - vb
  name: Options
  nameWithType: XCodeCapabilitySettings.BackgroundModesCapability.Options
  fullName: StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.Options
  type: Field
  source:
    id: Options
    path: ''
    startLine: 1641
  assemblies:
  - cs.temp.dll
  namespace: StansAssets.IOS.XCode
  syntax:
    content: public List<XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions> Options
    return:
      type: List{StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions}
    content.vb: Public Options As List(Of XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: StansAssets.IOS.XCode
  commentId: N:StansAssets.IOS.XCode
  name: StansAssets.IOS.XCode
  nameWithType: StansAssets.IOS.XCode
  fullName: StansAssets.IOS.XCode
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: StansAssets.IOS.XCode.XCodeCapabilitySettings.Capability
  commentId: T:StansAssets.IOS.XCode.XCodeCapabilitySettings.Capability
  parent: StansAssets.IOS.XCode
  name: XCodeCapabilitySettings.Capability
  nameWithType: XCodeCapabilitySettings.Capability
  fullName: StansAssets.IOS.XCode.XCodeCapabilitySettings.Capability
- uid: StansAssets.IOS.XCode.XCodeCapabilitySettings.Capability.Enabled
  commentId: F:StansAssets.IOS.XCode.XCodeCapabilitySettings.Capability.Enabled
  parent: StansAssets.IOS.XCode.XCodeCapabilitySettings.Capability
  name: Enabled
  nameWithType: XCodeCapabilitySettings.Capability.Enabled
  fullName: StansAssets.IOS.XCode.XCodeCapabilitySettings.Capability.Enabled
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: List{StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions}
  commentId: '!:List{StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions}'
  definition: List`1
  name: List<XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions>
  nameWithType: List<XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions>
  fullName: List<StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions>
  nameWithType.vb: List(Of XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions)
  fullName.vb: List(Of StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions)
  name.vb: List(Of XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions)
  spec.csharp:
  - uid: List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions
    name: XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions
    nameWithType: XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions
    fullName: StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions
    name: XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions
    nameWithType: XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions
    fullName: StansAssets.IOS.XCode.XCodeCapabilitySettings.BackgroundModesCapability.BackgroundModesOptions
  - name: )
    nameWithType: )
    fullName: )
- uid: List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: List<>
  nameWithType.vb: List(Of )
  fullName.vb: List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
